services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT}:8080"
    volumes:
      - ai-study-app-server-data:/app/backend/data
    env_file:
      - .env

  db:
    image: postgres:17
    container_name: db
    volumes:
      - ai-study-app-psql-data:/var/lib/postgresql/data
    tty: true
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: 'Asia/Tokyo'

volumes:
  ai-study-app-psql-data:
    driver: local
  ai-study-app-server-data:
    driver: local
